default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rad_on_development

test:
  <<: *default
  database: rad_on_test

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
